# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [2]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [3]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(Path("./Resources/applicants_data.csv"))

# Review the DataFrame

applicant_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Review the data types associated with the columns

applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [5]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns = ["EIN", "NAME"])

# Review the DataFrame
applicant_data_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [6]:
# Create a list of categorical variables 
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes == "object"].index)

# Display the categorical variables list

categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [7]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [8]:
# Encode the categorcal variables using OneHotEncoder

encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [9]:
# Create a DataFrame with the encoded variables

encoded_df = pd.DataFrame(encoded_data,columns = enc.get_feature_names(categorical_variables))

# Review the DataFrame

encoded_df.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [10]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
# My group member, Aaron, assisted me with these two lines.

numerical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes != "object"].index)
encoded_df = pd.concat([encoded_df, applicant_data_df[numerical_variables]], axis = 1)

# Review the Dataframe

encoded_df.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,STATUS,ASK_AMT,IS_SUCCESSFUL
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,108590,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,6692,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,142590,1

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [11]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df["IS_SUCCESSFUL"]

# Display a sample of y

y

0        1
1        1
2        0
3        1
4        1
        ..
34294    0
34295    0
34296    0
34297    1
34298    0
Name: IS_SUCCESSFUL, Length: 34299, dtype: int64

In [14]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns = ["IS_SUCCESSFUL"])

# Review the features DataFrame

X.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,STATUS,ASK_AMT
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,108590
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,6692
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,142590

### Step 6: Split the features and target sets into training and testing datasets.

In [15]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [16]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [17]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.loc[0])

# Review the number of features
number_input_features

116

In [18]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [19]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  4
# Review the number hidden nodes in the first layer
hidden_nodes_layer1

8

In [20]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 = 2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

2

In [21]:
# Create the Sequential model instance
nn = Sequential()

In [23]:
# Add the first hidden layer

nn.add(Dense(units = hidden_nodes_layer1, input_dim = number_input_features, activation = "relu"))

In [24]:
# Add the second hidden layer

nn.add(Dense(units = hidden_nodes_layer2, activation = "relu"))

In [25]:
# Add the output layer to the model specifying the number of output neurons and activation function

nn.add(Dense(units = number_output_neurons, activation = "sigmoid"))

In [26]:
# Display the Sequential model summary

nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 8)                 936
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 18
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 3
=================================================================
Total params: 1,029
Trainable params: 1,029
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [28]:
# Compile the Sequential model

nn.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])

In [29]:
# Fit the model using 50 epochs and the training data

nn.fit(X_train_scaled, y_train, epochs = 50)

Epoch 1/50
804/804 [==============================] - 1s 609us/step - loss: 0.6657 - accuracy: 0.6490
Epoch 2/50
804/804 [==============================] - 0s 599us/step - loss: 0.5643 - accuracy: 0.7272
Epoch 3/50
804/804 [==============================] - 0s 604us/step - loss: 0.5516 - accuracy: 0.7293
Epoch 4/50
804/804 [==============================] - 0s 597us/step - loss: 0.5553 - accuracy: 0.7232
Epoch 5/50
804/804 [==============================] - 0s 601us/step - loss: 0.5472 - accuracy: 0.7321
Epoch 6/50
804/804 [==============================] - 0s 610us/step - loss: 0.5495 - accuracy: 0.7288
Epoch 7/50
804/804 [==============================] - 0s 587us/step - loss: 0.5505 - accuracy: 0.7314
Epoch 8/50
804/804 [==============================] - 0s 587us/step - loss: 0.5481 - accuracy: 0.7298
Epoch 9/50
804/804 [==============================] - 0s 586us/step - loss: 0.5415 - accuracy: 0.7349
Epoch 10/50
804/804 [==============================] - 1s 648us/step - loss: 0.5466 - accuracy: 0.7318
Epoch 11/50
804/804 [==============================] - 0s 588us/step - loss: 0.5388 - accuracy: 0.7369
Epoch 12/50
804/804 [==============================] - 0s 587us/step - loss: 0.5444 - accuracy: 0.7352
Epoch 13/50
804/804 [==============================] - 0s 593us/step - loss: 0.5430 - accuracy: 0.7354
Epoch 14/50
804/804 [==============================] - 0s 612us/step - loss: 0.5464 - accuracy: 0.7294
Epoch 15/50
804/804 [==============================] - 0s 594us/step - loss: 0.5446 - accuracy: 0.7325
Epoch 16/50
804/804 [==============================] - 0s 614us/step - loss: 0.5506 - accuracy: 0.7281
Epoch 17/50
804/804 [==============================] - 0s 600us/step - loss: 0.5436 - accuracy: 0.7348
Epoch 18/50
804/804 [==============================] - 0s 602us/step - loss: 0.5364 - accuracy: 0.7368
Epoch 19/50
804/804 [==============================] - 0s 600us/step - loss: 0.5409 - accuracy: 0.7339
Epoch 20/50
804/804 [==============================] - 0s 604us/step - loss: 0.5424 - accuracy: 0.7355
Epoch 21/50
804/804 [==============================] - 0s 601us/step - loss: 0.5447 - accuracy: 0.7347
Epoch 22/50
804/804 [==============================] - 1s 652us/step - loss: 0.5425 - accuracy: 0.7365
Epoch 23/50
804/804 [==============================] - 1s 655us/step - loss: 0.5413 - accuracy: 0.7358
Epoch 24/50
804/804 [==============================] - 0s 604us/step - loss: 0.5461 - accuracy: 0.7314
Epoch 25/50
804/804 [==============================] - 0s 596us/step - loss: 0.5409 - accuracy: 0.7372
Epoch 26/50
804/804 [==============================] - 0s 602us/step - loss: 0.5380 - accuracy: 0.7370
Epoch 27/50
804/804 [==============================] - 1s 640us/step - loss: 0.5412 - accuracy: 0.7354
Epoch 28/50
804/804 [==============================] - 1s 659us/step - loss: 0.5355 - accuracy: 0.7385
Epoch 29/50
804/804 [==============================] - 1s 631us/step - loss: 0.5426 - accuracy: 0.7327
Epoch 30/50
804/804 [==============================] - 1s 652us/step - loss: 0.5418 - accuracy: 0.7345
Epoch 31/50
804/804 [==============================] - 1s 720us/step - loss: 0.5379 - accuracy: 0.7373
Epoch 32/50
804/804 [==============================] - 0s 606us/step - loss: 0.5391 - accuracy: 0.7369
Epoch 33/50
804/804 [==============================] - 1s 654us/step - loss: 0.5405 - accuracy: 0.7365
Epoch 34/50
804/804 [==============================] - 0s 610us/step - loss: 0.5430 - accuracy: 0.7327
Epoch 35/50
804/804 [==============================] - 1s 630us/step - loss: 0.5434 - accuracy: 0.7314
Epoch 36/50
804/804 [==============================] - 0s 620us/step - loss: 0.5420 - accuracy: 0.7320
Epoch 37/50
804/804 [==============================] - 0s 601us/step - loss: 0.5420 - accuracy: 0.7326
Epoch 38/50
804/804 [==============================] - 0s 604us/step - loss: 0.5443 - accuracy: 0.7321
Epoch 39/50
804/804 [==============================] - 0s 609us/step - loss: 0.5334 - accuracy: 0.7399
Epoch 40/50
804/804 [==============================] - 0s 620us/step - loss: 0.5402 - accuracy: 0.7336
Epoch 41/50
804/804 [==============================] - 0s 594us/step - loss: 0.5375 - accuracy: 0.7377
Epoch 42/50
804/804 [==============================] - 0s 614us/step - loss: 0.5433 - accuracy: 0.7315
Epoch 43/50
804/804 [==============================] - 0s 615us/step - loss: 0.5393 - accuracy: 0.7333
Epoch 44/50
804/804 [==============================] - 0s 608us/step - loss: 0.5404 - accuracy: 0.7331
Epoch 45/50
804/804 [==============================] - 1s 651us/step - loss: 0.5395 - accuracy: 0.7349
Epoch 46/50
804/804 [==============================] - 1s 639us/step - loss: 0.5396 - accuracy: 0.7338
Epoch 47/50
804/804 [==============================] - 0s 608us/step - loss: 0.5431 - accuracy: 0.7314
Epoch 48/50
804/804 [==============================] - 0s 590us/step - loss: 0.5362 - accuracy: 0.7395
Epoch 49/50
804/804 [==============================] - 1s 636us/step - loss: 0.5375 - accuracy: 0.7381
Epoch 50/50
804/804 [==============================] - 0s 593us/step - loss: 0.5384 - accuracy: 0.7367

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [30]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose = 2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5515 - accuracy: 0.7292
Loss: 0.5515149831771851, Accuracy: 0.7292128205299377

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [31]:
# Set the model's file path
file_path = Path("./H5/AlphabetSoup.h5")

# Export your model to a HDF5 file

nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [32]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [33]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [34]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = 2

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

2

In [38]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [42]:
# Second,third hidden layers
hidden_nodes_layer2_A1 = 4
hidden_nodes_layer3_A1 = 16

nn_A1.add(Dense(units = hidden_nodes_layer1_A1, input_dim = number_input_features, activation = "relu"))
nn_A1.add(Dense(units = hidden_nodes_layer2_A1, activation = "relu"))
nn_A1.add(Dense(units = hidden_nodes_layer3_A1, activation = "relu"))

# Output layer
nn_A1.add(Dense(units = number_output_neurons, activation = "sigmoid"))

# Check the structure of the model

nn_A1.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_9 (Dense)              (None, 2)                 234
_________________________________________________________________
dense_10 (Dense)             (None, 4)                 12
_________________________________________________________________
dense_11 (Dense)             (None, 8)                 40
_________________________________________________________________
dense_12 (Dense)             (None, 1)                 9
_________________________________________________________________
dense_13 (Dense)             (None, 2)                 4
_________________________________________________________________
dense_14 (Dense)             (None, 4)                 12
_________________________________________________________________
dense_15 (Dense)             (None, 16)                80
_________________________________________________________________
dense_16 (Dense)             (None, 1)                 17
=================================================================
Total params: 408
Trainable params: 408
Non-trainable params: 0
_________________________________________________________________

In [43]:
# Compile the Sequential model

nn_A1.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])

In [44]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs = 50)

Epoch 1/50
804/804 [==============================] - 1s 785us/step - loss: 0.6918 - accuracy: 0.5338
Epoch 2/50
804/804 [==============================] - 1s 766us/step - loss: 0.6914 - accuracy: 0.5296
Epoch 3/50
804/804 [==============================] - 1s 779us/step - loss: 0.6909 - accuracy: 0.5338
Epoch 4/50
804/804 [==============================] - 1s 794us/step - loss: 0.6900 - accuracy: 0.5398
Epoch 5/50
804/804 [==============================] - 1s 784us/step - loss: 0.6910 - accuracy: 0.5331
Epoch 6/50
804/804 [==============================] - 1s 674us/step - loss: 0.6907 - accuracy: 0.5355
Epoch 7/50
804/804 [==============================] - 1s 658us/step - loss: 0.6915 - accuracy: 0.5293
Epoch 8/50
804/804 [==============================] - 1s 682us/step - loss: 0.6911 - accuracy: 0.5322
Epoch 9/50
804/804 [==============================] - 1s 662us/step - loss: 0.6909 - accuracy: 0.5339
Epoch 10/50
804/804 [==============================] - 1s 708us/step - loss: 0.6913 - accuracy: 0.5306
Epoch 11/50
804/804 [==============================] - 1s 698us/step - loss: 0.6907 - accuracy: 0.5348
Epoch 12/50
804/804 [==============================] - 1s 664us/step - loss: 0.6907 - accuracy: 0.5353
Epoch 13/50
804/804 [==============================] - 1s 669us/step - loss: 0.6915 - accuracy: 0.5287
Epoch 14/50
804/804 [==============================] - 1s 678us/step - loss: 0.6914 - accuracy: 0.5300
Epoch 15/50
804/804 [==============================] - 1s 667us/step - loss: 0.6907 - accuracy: 0.5351
Epoch 16/50
804/804 [==============================] - 1s 664us/step - loss: 0.6907 - accuracy: 0.5352
Epoch 17/50
804/804 [==============================] - 1s 696us/step - loss: 0.6910 - accuracy: 0.5332
Epoch 18/50
804/804 [==============================] - 1s 713us/step - loss: 0.6903 - accuracy: 0.5380
Epoch 19/50
804/804 [==============================] - 1s 700us/step - loss: 0.6907 - accuracy: 0.5352
Epoch 20/50
804/804 [==============================] - 1s 698us/step - loss: 0.6911 - accuracy: 0.5319
Epoch 21/50
804/804 [==============================] - 1s 672us/step - loss: 0.6917 - accuracy: 0.5277
Epoch 22/50
804/804 [==============================] - 1s 669us/step - loss: 0.6909 - accuracy: 0.5334
Epoch 23/50
804/804 [==============================] - 1s 691us/step - loss: 0.6912 - accuracy: 0.5313
Epoch 24/50
804/804 [==============================] - 1s 708us/step - loss: 0.6909 - accuracy: 0.5334
Epoch 25/50
804/804 [==============================] - 1s 683us/step - loss: 0.6911 - accuracy: 0.5326
Epoch 26/50
804/804 [==============================] - 1s 682us/step - loss: 0.6901 - accuracy: 0.5397
Epoch 27/50
804/804 [==============================] - 1s 671us/step - loss: 0.6908 - accuracy: 0.5343
Epoch 28/50
804/804 [==============================] - 1s 686us/step - loss: 0.6913 - accuracy: 0.5302
Epoch 29/50
804/804 [==============================] - 1s 677us/step - loss: 0.6912 - accuracy: 0.5317
Epoch 30/50
804/804 [==============================] - 1s 677us/step - loss: 0.6910 - accuracy: 0.5332
Epoch 31/50
804/804 [==============================] - 1s 696us/step - loss: 0.6909 - accuracy: 0.5335
Epoch 32/50
804/804 [==============================] - 1s 691us/step - loss: 0.6910 - accuracy: 0.5329
Epoch 33/50
804/804 [==============================] - 1s 722us/step - loss: 0.6908 - accuracy: 0.5347
Epoch 34/50
804/804 [==============================] - 1s 671us/step - loss: 0.6911 - accuracy: 0.5320
Epoch 35/50
804/804 [==============================] - 1s 707us/step - loss: 0.6905 - accuracy: 0.5364
Epoch 36/50
804/804 [==============================] - 1s 764us/step - loss: 0.6910 - accuracy: 0.5329
Epoch 37/50
804/804 [==============================] - 1s 763us/step - loss: 0.6911 - accuracy: 0.5326
Epoch 38/50
804/804 [==============================] - 1s 681us/step - loss: 0.6914 - accuracy: 0.5304
Epoch 39/50
804/804 [==============================] - 1s 824us/step - loss: 0.6912 - accuracy: 0.5316
Epoch 40/50
804/804 [==============================] - 1s 712us/step - loss: 0.6910 - accuracy: 0.5329
Epoch 41/50
804/804 [==============================] - 1s 733us/step - loss: 0.6909 - accuracy: 0.5337
Epoch 42/50
804/804 [==============================] - 1s 706us/step - loss: 0.6915 - accuracy: 0.5295
Epoch 43/50
804/804 [==============================] - 1s 707us/step - loss: 0.6898 - accuracy: 0.5409
Epoch 44/50
804/804 [==============================] - 1s 726us/step - loss: 0.6908 - accuracy: 0.5344
Epoch 45/50
804/804 [==============================] - 1s 681us/step - loss: 0.6911 - accuracy: 0.5323
Epoch 46/50
804/804 [==============================] - 1s 672us/step - loss: 0.6913 - accuracy: 0.5306
Epoch 47/50
804/804 [==============================] - 1s 681us/step - loss: 0.6911 - accuracy: 0.5321
Epoch 48/50
804/804 [==============================] - 1s 710us/step - loss: 0.6912 - accuracy: 0.5318
Epoch 49/50
804/804 [==============================] - 1s 721us/step - loss: 0.6915 - accuracy: 0.5293
Epoch 50/50
804/804 [==============================] - 1s 732us/step - loss: 0.6909 - accuracy: 0.5336

#### Alternative Model 2

In [45]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [ ]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [46]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 2
# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

2

In [47]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [48]:
# First hidden layer

hidden_nodes_layer2_A2 = 6
hidden_nodes_layer3_A2 = 2

nn_A2.add(Dense(units = hidden_nodes_layer1_A2, input_dim = number_input_features, activation = "selu"))
nn_A2.add(Dense(units = hidden_nodes_layer2_A2, activation = "selu"))
nn_A2.add(Dense(units = hidden_nodes_layer3_A2, activation = "selu"))

# Output layer

nn_A2.add(Dense(units = number_output_neurons, activation = "sigmoid"))

# Check the structure of the model

nn_A2.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_17 (Dense)             (None, 2)                 234
_________________________________________________________________
dense_18 (Dense)             (None, 6)                 18
_________________________________________________________________
dense_19 (Dense)             (None, 2)                 14
_________________________________________________________________
dense_20 (Dense)             (None, 1)                 3
=================================================================
Total params: 269
Trainable params: 269
Non-trainable params: 0
_________________________________________________________________

In [49]:
# Compile the model

nn_A2.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])

In [50]:
# Fit the model

nn_A2.fit(X_train_scaled, y_train, epochs = 50)

Epoch 1/50
804/804 [==============================] - 1s 567us/step - loss: 0.6490 - accuracy: 0.6270
Epoch 2/50
804/804 [==============================] - 0s 578us/step - loss: 0.5745 - accuracy: 0.7286
Epoch 3/50
804/804 [==============================] - 0s 555us/step - loss: 0.5722 - accuracy: 0.7262
Epoch 4/50
804/804 [==============================] - 0s 552us/step - loss: 0.5705 - accuracy: 0.7254
Epoch 5/50
804/804 [==============================] - 0s 549us/step - loss: 0.5709 - accuracy: 0.7212
Epoch 6/50
804/804 [==============================] - 0s 606us/step - loss: 0.5614 - accuracy: 0.7311
Epoch 7/50
804/804 [==============================] - 0s 552us/step - loss: 0.5671 - accuracy: 0.7251
Epoch 8/50
804/804 [==============================] - 0s 578us/step - loss: 0.5687 - accuracy: 0.7231
Epoch 9/50
804/804 [==============================] - 0s 547us/step - loss: 0.5597 - accuracy: 0.7305
Epoch 10/50
804/804 [==============================] - 0s 596us/step - loss: 0.5678 - accuracy: 0.7228
Epoch 11/50
804/804 [==============================] - 0s 551us/step - loss: 0.5564 - accuracy: 0.7316
Epoch 12/50
804/804 [==============================] - 0s 549us/step - loss: 0.5620 - accuracy: 0.7266
Epoch 13/50
804/804 [==============================] - 0s 572us/step - loss: 0.5619 - accuracy: 0.7251
Epoch 14/50
804/804 [==============================] - 0s 561us/step - loss: 0.5590 - accuracy: 0.7271
Epoch 15/50
804/804 [==============================] - 0s 605us/step - loss: 0.5612 - accuracy: 0.7248
Epoch 16/50
804/804 [==============================] - 0s 602us/step - loss: 0.5564 - accuracy: 0.7284
Epoch 17/50
804/804 [==============================] - 0s 581us/step - loss: 0.5559 - accuracy: 0.7297
Epoch 18/50
804/804 [==============================] - 0s 565us/step - loss: 0.5537 - accuracy: 0.7317
Epoch 19/50
804/804 [==============================] - 0s 607us/step - loss: 0.5553 - accuracy: 0.7271
Epoch 20/50
804/804 [==============================] - 0s 593us/step - loss: 0.5593 - accuracy: 0.7245
Epoch 21/50
804/804 [==============================] - 0s 616us/step - loss: 0.5629 - accuracy: 0.7210
Epoch 22/50
804/804 [==============================] - 0s 587us/step - loss: 0.5546 - accuracy: 0.7297
Epoch 23/50
804/804 [==============================] - 0s 560us/step - loss: 0.5523 - accuracy: 0.7310
Epoch 24/50
804/804 [==============================] - 0s 611us/step - loss: 0.5592 - accuracy: 0.7254
Epoch 25/50
804/804 [==============================] - 0s 563us/step - loss: 0.5555 - accuracy: 0.7289
Epoch 26/50
804/804 [==============================] - 0s 558us/step - loss: 0.5551 - accuracy: 0.7252
Epoch 27/50
804/804 [==============================] - 0s 555us/step - loss: 0.5556 - accuracy: 0.7257
Epoch 28/50
804/804 [==============================] - 0s 553us/step - loss: 0.5511 - accuracy: 0.7307
Epoch 29/50
804/804 [==============================] - 0s 554us/step - loss: 0.5515 - accuracy: 0.7313
Epoch 30/50
804/804 [==============================] - 0s 561us/step - loss: 0.5543 - accuracy: 0.7303
Epoch 31/50
804/804 [==============================] - 0s 556us/step - loss: 0.5577 - accuracy: 0.7260
Epoch 32/50
804/804 [==============================] - 0s 579us/step - loss: 0.5571 - accuracy: 0.7259
Epoch 33/50
804/804 [==============================] - 0s 574us/step - loss: 0.5500 - accuracy: 0.7321
Epoch 34/50
804/804 [==============================] - 0s 579us/step - loss: 0.5540 - accuracy: 0.7261
Epoch 35/50
804/804 [==============================] - 0s 575us/step - loss: 0.5541 - accuracy: 0.7273
Epoch 36/50
804/804 [==============================] - 0s 556us/step - loss: 0.5520 - accuracy: 0.7286
Epoch 37/50
804/804 [==============================] - 0s 561us/step - loss: 0.5567 - accuracy: 0.7265
Epoch 38/50
804/804 [==============================] - 0s 561us/step - loss: 0.5580 - accuracy: 0.7218
Epoch 39/50
804/804 [==============================] - 0s 558us/step - loss: 0.5528 - accuracy: 0.7306
Epoch 40/50
804/804 [==============================] - 0s 595us/step - loss: 0.5516 - accuracy: 0.7332
Epoch 41/50
804/804 [==============================] - 0s 600us/step - loss: 0.5510 - accuracy: 0.7341
Epoch 42/50
804/804 [==============================] - 0s 576us/step - loss: 0.5576 - accuracy: 0.7267
Epoch 43/50
804/804 [==============================] - 0s 580us/step - loss: 0.5464 - accuracy: 0.7338
Epoch 44/50
804/804 [==============================] - 0s 553us/step - loss: 0.5508 - accuracy: 0.7311
Epoch 45/50
804/804 [==============================] - 0s 557us/step - loss: 0.5579 - accuracy: 0.7236
Epoch 46/50
804/804 [==============================] - 0s 558us/step - loss: 0.5530 - accuracy: 0.7286
Epoch 47/50
804/804 [==============================] - 0s 558us/step - loss: 0.5477 - accuracy: 0.7354
Epoch 48/50
804/804 [==============================] - 0s 555us/step - loss: 0.5538 - accuracy: 0.7273
Epoch 49/50
804/804 [==============================] - 0s 580us/step - loss: 0.5534 - accuracy: 0.7281
Epoch 50/50
804/804 [==============================] - 0s 563us/step - loss: 0.5511 - accuracy: 0.7302

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [51]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose = 2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.5515 - accuracy: 0.7292
Loss: 0.5515149831771851, Accuracy: 0.7292128205299377

In [52]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test, verbose = 2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 0.6915 - accuracy: 0.5292
Loss: 0.6914864778518677, Accuracy: 0.5292128324508667

In [53]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose = 2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 0.5579 - accuracy: 0.7261
Loss: 0.5578685998916626, Accuracy: 0.726064145565033

### Step 3: Save each of your alternative models as an HDF5 file.

In [54]:
# Set the file path for the first alternative model
file_path = Path("./H5/AlphabetSoup_A1.h5")

# Export your model to a HDF5 file

nn_A1.save(file_path)

In [55]:
# Set the file path for the second alternative model
file_path = Path("./H5/AlphabetSoup_A2.h5")

# Export your model to a HDF5 file

nn_A2.save(file_path)